baseURL: http://silviadeluzio.github.io/
languageCode: en-us
title: Silvia Deluzio

theme: "PaperMod"
paginate: 6

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Silvia Deluzio
  description: "Silvia Deluzio"
  keywords: [Blog, Portfolio, PaperMod]
  author: Silvia Deluzio
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.ico"
    favicon32x32: "/favicon-32x32.ico"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Silvia Deluzio"

  # profile-mode
  profileMode:
    enabled: true
    title: "Silvia Deluzio"
    subtitle: "I am a business analyst and Computer Engineering student, focused on data science and interested in the intersection between tech and fashion."
    buttons:
        - name: Archive
        url: "/archive"
        - name: Github
        url: "https://github.com/"

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com/in/silvia-deluzio"
    - name: email
      url: "mailto:dlzsilvia2210@gmail.com"
    - name: github
      url: "https://github.com/silviadeluzio"

  # home-info mode
  homeInfoParams:
    Title: "Silvia Deluzio"
    Content: I am a business analyst and Computer Engineering student, focused on data science and interested in the intersection between tech and fashion.

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com/in/silvia-deluzio"
    - name: email
      url: "mailto:dlzsilvia2210@gmail.com"
    - name: github
      url: "https://github.com/silviadeluzio"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 15
    - identifier: contacts
      name: Contact me
      url: mailto:dlzsilvia2210@gmail.com
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
